name = "karirhub-rss"
main = "src/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "development"
API_BASE_URL = "https://api.kemnaker.go.id/karirhub/catalogue/v1"
CACHE_TTL = "1800"
MAX_JOBS_PER_FEED = "20"
RSS_TITLE = "Lowongan Kerja Terbaru - KarirHub Indonesia"
RSS_DESCRIPTION = "Feed lowongan kerja resmi dari Kementerian Ketenagakerjaan Indonesia"
RSS_LANGUAGE = "id"
RSS_WEBMASTER = "admin@karirhub.com"
RSS_GENERATOR = "Cloudflare Worker RSS Generator v1.0"
ENABLE_ANALYTICS = "true"
LOG_LEVEL = "info"

# KV namespace for caching
[[kv_namespaces]]
binding = "RSS_CACHE"
id = "2e55b61a8a1343909bfa224f157b037c"
preview_id = "2e55b61a8a1343909bfa224f157b037c"  # Using production ID for preview

# D1 database for analytics
[[d1_databases]]
binding = "RSS_ANALYTICS"
database_name = "karirhub-rss-analytics"
database_id = "5b114d74-8490-4cfa-a5dc-f2c2a142f686"

# Production environment
[env.production]
name = "karirhub-rss-prod"

[env.production.vars]
ENVIRONMENT = "production"
CACHE_TTL = "1800"
MAX_JOBS_PER_FEED = "50"
LOG_LEVEL = "warn"

# Staging environment
[env.staging]
name = "karirhub-rss-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
CACHE_TTL = "900"
MAX_JOBS_PER_FEED = "10"
LOG_LEVEL = "debug"

# Limits and configuration
[limits]
cpu_ms = 50000

# Build configuration
[build]
command = ""

# Triggers for scheduled updates
[triggers]
crons = ["*/15 * * * *"]  # Every 15 minutes