name = "karirhub-rss"
main = "src/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (optimized for free plan)
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://api.kemnaker.go.id/karirhub/catalogue/v1"
CACHE_TTL = "3600"  # 1 hour cache for free plan efficiency
MAX_JOBS_PER_FEED = "30"  # Optimized for free plan
RSS_TITLE = "Lowongan Kerja Terbaru - KarirHub Indonesia"
RSS_DESCRIPTION = "Feed lowongan kerja resmi dari Kementerian Ketenagakerjaan Indonesia"
RSS_LANGUAGE = "id"
RSS_WEBMASTER = "admin@karirhub.com"
RSS_GENERATOR = "Cloudflare Worker RSS Generator v1.0"
ENABLE_ANALYTICS = "false"  # Disabled to save D1 operations on free plan
LOG_LEVEL = "info"

# KV namespace for caching
[[kv_namespaces]]
binding = "RSS_CACHE"
id = "2e55b61a8a1343909bfa224f157b037c"
preview_id = "2e55b61a8a1343909bfa224f157b037c"  # Using production ID for preview

# D1 database for analytics
[[d1_databases]]
binding = "RSS_ANALYTICS"
database_name = "karirhub-rss-analytics"
database_id = "5b114d74-8490-4cfa-a5dc-f2c2a142f686"

# Simplified configuration - single environment for free plan efficiency

# Build configuration
[build]
command = ""

# Triggers for scheduled updates (hourly for free plan optimization)
[triggers]
crons = ["0 * * * *"]  # Every hour (free plan friendly)